spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.111.10:3306/pig
    username: root
    password: wa1234
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
